server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/transaction?currentSchema=public
    username: postgres
    password: postgres
  flyway:
    baseline-version: 1
    baseline-on-migrate: true
    mixed: true

#Email Config
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${email}
    password: ${password}
    protocol: smtp
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com