/*
 * This file is generated by jOOQ.
 */
package ge.tsu.transaction.classes;


import ge.tsu.transaction.classes.tables.FlywaySchemaHistory;
import ge.tsu.transaction.classes.tables.Transaction;
import ge.tsu.transaction.classes.tables.User;
import ge.tsu.transaction.classes.tables.records.FlywaySchemaHistoryRecord;
import ge.tsu.transaction.classes.tables.records.TransactionRecord;
import ge.tsu.transaction.classes.tables.records.UserRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in 
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<FlywaySchemaHistoryRecord> FLYWAY_SCHEMA_HISTORY_PK = Internal.createUniqueKey(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, DSL.name("flyway_schema_history_pk"), new TableField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK }, true);
    public static final UniqueKey<TransactionRecord> STATUS_PK = Internal.createUniqueKey(Transaction.TRANSACTION, DSL.name("status_pk"), new TableField[] { Transaction.TRANSACTION.ID }, true);
    public static final UniqueKey<UserRecord> USER_PKEY = Internal.createUniqueKey(User.USER, DSL.name("user_pkey"), new TableField[] { User.USER.ID }, true);
}
