/*
 * This file is generated by jOOQ.
 */
package ge.tsu.transaction.classes;


import ge.tsu.transaction.classes.tables.FlywaySchemaHistory;
import ge.tsu.transaction.classes.tables.Transaction;
import ge.tsu.transaction.classes.tables.User;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.transaction</code>.
     */
    public static final Transaction TRANSACTION = Transaction.TRANSACTION;

    /**
     * The table <code>public.user</code>.
     */
    public static final User USER = User.USER;
}
