/*
 * This file is generated by jOOQ.
 */
package ge.tsu.transaction.classes.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Transaction implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       id;
    private String        documentNumber;
    private LocalDateTime postDate;
    private Double        amount;
    private Integer       receiverId;
    private Integer       senderId;

    public Transaction() {}

    public Transaction(Transaction value) {
        this.id = value.id;
        this.documentNumber = value.documentNumber;
        this.postDate = value.postDate;
        this.amount = value.amount;
        this.receiverId = value.receiverId;
        this.senderId = value.senderId;
    }

    public Transaction(
        Integer       id,
        String        documentNumber,
        LocalDateTime postDate,
        Double        amount,
        Integer       receiverId,
        Integer       senderId
    ) {
        this.id = id;
        this.documentNumber = documentNumber;
        this.postDate = postDate;
        this.amount = amount;
        this.receiverId = receiverId;
        this.senderId = senderId;
    }

    /**
     * Getter for <code>public.transaction.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.transaction.id</code>.
     */
    public Transaction setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.transaction.document_number</code>.
     */
    public String getDocumentNumber() {
        return this.documentNumber;
    }

    /**
     * Setter for <code>public.transaction.document_number</code>.
     */
    public Transaction setDocumentNumber(String documentNumber) {
        this.documentNumber = documentNumber;
        return this;
    }

    /**
     * Getter for <code>public.transaction.post_date</code>.
     */
    public LocalDateTime getPostDate() {
        return this.postDate;
    }

    /**
     * Setter for <code>public.transaction.post_date</code>.
     */
    public Transaction setPostDate(LocalDateTime postDate) {
        this.postDate = postDate;
        return this;
    }

    /**
     * Getter for <code>public.transaction.amount</code>.
     */
    public Double getAmount() {
        return this.amount;
    }

    /**
     * Setter for <code>public.transaction.amount</code>.
     */
    public Transaction setAmount(Double amount) {
        this.amount = amount;
        return this;
    }

    /**
     * Getter for <code>public.transaction.receiver_id</code>.
     */
    public Integer getReceiverId() {
        return this.receiverId;
    }

    /**
     * Setter for <code>public.transaction.receiver_id</code>.
     */
    public Transaction setReceiverId(Integer receiverId) {
        this.receiverId = receiverId;
        return this;
    }

    /**
     * Getter for <code>public.transaction.sender_id</code>.
     */
    public Integer getSenderId() {
        return this.senderId;
    }

    /**
     * Setter for <code>public.transaction.sender_id</code>.
     */
    public Transaction setSenderId(Integer senderId) {
        this.senderId = senderId;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Transaction (");

        sb.append(id);
        sb.append(", ").append(documentNumber);
        sb.append(", ").append(postDate);
        sb.append(", ").append(amount);
        sb.append(", ").append(receiverId);
        sb.append(", ").append(senderId);

        sb.append(")");
        return sb.toString();
    }
}
