/*
 * This file is generated by jOOQ.
 */
package ge.tsu.transaction.classes.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private String  identificationNumber;
    private String  accountNumber;
    private Double  amount;
    private String  name;
    private String  surname;
    private String  mobileNumber;
    private String  emailAddress;
    private String  password;

    public User() {}

    public User(User value) {
        this.id = value.id;
        this.identificationNumber = value.identificationNumber;
        this.accountNumber = value.accountNumber;
        this.amount = value.amount;
        this.name = value.name;
        this.surname = value.surname;
        this.mobileNumber = value.mobileNumber;
        this.emailAddress = value.emailAddress;
        this.password = value.password;
    }

    public User(
        Integer id,
        String  identificationNumber,
        String  accountNumber,
        Double  amount,
        String  name,
        String  surname,
        String  mobileNumber,
        String  emailAddress,
        String  password
    ) {
        this.id = id;
        this.identificationNumber = identificationNumber;
        this.accountNumber = accountNumber;
        this.amount = amount;
        this.name = name;
        this.surname = surname;
        this.mobileNumber = mobileNumber;
        this.emailAddress = emailAddress;
        this.password = password;
    }

    /**
     * Getter for <code>public.user.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.user.id</code>.
     */
    public User setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>public.user.identification_number</code>.
     */
    public String getIdentificationNumber() {
        return this.identificationNumber;
    }

    /**
     * Setter for <code>public.user.identification_number</code>.
     */
    public User setIdentificationNumber(String identificationNumber) {
        this.identificationNumber = identificationNumber;
        return this;
    }

    /**
     * Getter for <code>public.user.account_number</code>.
     */
    public String getAccountNumber() {
        return this.accountNumber;
    }

    /**
     * Setter for <code>public.user.account_number</code>.
     */
    public User setAccountNumber(String accountNumber) {
        this.accountNumber = accountNumber;
        return this;
    }

    /**
     * Getter for <code>public.user.amount</code>.
     */
    public Double getAmount() {
        return this.amount;
    }

    /**
     * Setter for <code>public.user.amount</code>.
     */
    public User setAmount(Double amount) {
        this.amount = amount;
        return this;
    }

    /**
     * Getter for <code>public.user.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>public.user.name</code>.
     */
    public User setName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Getter for <code>public.user.surname</code>.
     */
    public String getSurname() {
        return this.surname;
    }

    /**
     * Setter for <code>public.user.surname</code>.
     */
    public User setSurname(String surname) {
        this.surname = surname;
        return this;
    }

    /**
     * Getter for <code>public.user.mobile_number</code>.
     */
    public String getMobileNumber() {
        return this.mobileNumber;
    }

    /**
     * Setter for <code>public.user.mobile_number</code>.
     */
    public User setMobileNumber(String mobileNumber) {
        this.mobileNumber = mobileNumber;
        return this;
    }

    /**
     * Getter for <code>public.user.email_address</code>.
     */
    public String getEmailAddress() {
        return this.emailAddress;
    }

    /**
     * Setter for <code>public.user.email_address</code>.
     */
    public User setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress;
        return this;
    }

    /**
     * Getter for <code>public.user.password</code>.
     */
    public String getPassword() {
        return this.password;
    }

    /**
     * Setter for <code>public.user.password</code>.
     */
    public User setPassword(String password) {
        this.password = password;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("User (");

        sb.append(id);
        sb.append(", ").append(identificationNumber);
        sb.append(", ").append(accountNumber);
        sb.append(", ").append(amount);
        sb.append(", ").append(name);
        sb.append(", ").append(surname);
        sb.append(", ").append(mobileNumber);
        sb.append(", ").append(emailAddress);
        sb.append(", ").append(password);

        sb.append(")");
        return sb.toString();
    }
}
