/*
 * This file is generated by jOOQ.
 */
package ge.tsu.transaction.classes.tables.records;


import ge.tsu.transaction.classes.tables.Transaction;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TransactionRecord extends UpdatableRecordImpl<TransactionRecord> implements Record6<Integer, String, LocalDateTime, Double, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.transaction.id</code>.
     */
    public TransactionRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.transaction.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.transaction.document_number</code>.
     */
    public TransactionRecord setDocumentNumber(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.transaction.document_number</code>.
     */
    public String getDocumentNumber() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.transaction.post_date</code>.
     */
    public TransactionRecord setPostDate(LocalDateTime value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.transaction.post_date</code>.
     */
    public LocalDateTime getPostDate() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>public.transaction.amount</code>.
     */
    public TransactionRecord setAmount(Double value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.transaction.amount</code>.
     */
    public Double getAmount() {
        return (Double) get(3);
    }

    /**
     * Setter for <code>public.transaction.receiver_id</code>.
     */
    public TransactionRecord setReceiverId(Integer value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.transaction.receiver_id</code>.
     */
    public Integer getReceiverId() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.transaction.sender_id</code>.
     */
    public TransactionRecord setSenderId(Integer value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.transaction.sender_id</code>.
     */
    public Integer getSenderId() {
        return (Integer) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, String, LocalDateTime, Double, Integer, Integer> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, String, LocalDateTime, Double, Integer, Integer> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Transaction.TRANSACTION.ID;
    }

    @Override
    public Field<String> field2() {
        return Transaction.TRANSACTION.DOCUMENT_NUMBER;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return Transaction.TRANSACTION.POST_DATE;
    }

    @Override
    public Field<Double> field4() {
        return Transaction.TRANSACTION.AMOUNT;
    }

    @Override
    public Field<Integer> field5() {
        return Transaction.TRANSACTION.RECEIVER_ID;
    }

    @Override
    public Field<Integer> field6() {
        return Transaction.TRANSACTION.SENDER_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getDocumentNumber();
    }

    @Override
    public LocalDateTime component3() {
        return getPostDate();
    }

    @Override
    public Double component4() {
        return getAmount();
    }

    @Override
    public Integer component5() {
        return getReceiverId();
    }

    @Override
    public Integer component6() {
        return getSenderId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getDocumentNumber();
    }

    @Override
    public LocalDateTime value3() {
        return getPostDate();
    }

    @Override
    public Double value4() {
        return getAmount();
    }

    @Override
    public Integer value5() {
        return getReceiverId();
    }

    @Override
    public Integer value6() {
        return getSenderId();
    }

    @Override
    public TransactionRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public TransactionRecord value2(String value) {
        setDocumentNumber(value);
        return this;
    }

    @Override
    public TransactionRecord value3(LocalDateTime value) {
        setPostDate(value);
        return this;
    }

    @Override
    public TransactionRecord value4(Double value) {
        setAmount(value);
        return this;
    }

    @Override
    public TransactionRecord value5(Integer value) {
        setReceiverId(value);
        return this;
    }

    @Override
    public TransactionRecord value6(Integer value) {
        setSenderId(value);
        return this;
    }

    @Override
    public TransactionRecord values(Integer value1, String value2, LocalDateTime value3, Double value4, Integer value5, Integer value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TransactionRecord
     */
    public TransactionRecord() {
        super(Transaction.TRANSACTION);
    }

    /**
     * Create a detached, initialised TransactionRecord
     */
    public TransactionRecord(Integer id, String documentNumber, LocalDateTime postDate, Double amount, Integer receiverId, Integer senderId) {
        super(Transaction.TRANSACTION);

        setId(id);
        setDocumentNumber(documentNumber);
        setPostDate(postDate);
        setAmount(amount);
        setReceiverId(receiverId);
        setSenderId(senderId);
    }
}
